global:
  resolve_timeout: 5m
templates:
  - '/etc/alertmanager/template/*.tmpl'
receivers:
  - name: Default
  - name: slack
    slack_configs:
      - channel: demo
        api_url: >-
          https://hooks.slack.com/services/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
route:
  group_by: ['alertname', 'cluster', 'service']
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 3h
  routes:
    - receiver: slack
      match:
        severity: critical