apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulate-load
  labels:
    owner: org1
    app: simulate-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulate-load
  template:
    metadata:
      labels:
        app: simulate-load
    spec:
      containers:
      - name: simulate-load
        image: quay.io/alegros/simulate-load
        ports:
        - containerPort: 8080
